name: Build & Release linpeas CTF

on:
  push:
    tags:
      - "*"   # Ejecuta en cada tag (p.ej. v1.2.3)

permissions:
  contents: write  # necesario para crear releases y subir assets

jobs:
  Build_and_release_linpeas_ctf:
    runs-on: ubuntu-latest

    steps:
      # Checkout (como en el original)
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      # (Opcional) muestra versión de Go si tu script la necesita; si no, puedes borrar esto
      # - uses: actions/setup-go@v5
      #   with:
      #     go-version: 'stable'

      # Build: corre tu script desde el repo
      - name: Build linpeas CTF
        run: |
          python3 -m pip install PyYAML
          chmod +x linPEAS/buildCustom.sh
          ./linPEAS/buildCustom.sh

      # Verifica que el build generó el archivo esperado
      - name: Check built file
        run: |
          if [ ! -f /tmp/linpeas_ctf.sh ]; then
            echo "❌ No se generó /tmp/linpeas_ctf.sh"
            exit 1
          fi
          file /tmp/linpeas_ctf.sh
          ls -lh /tmp/linpeas_ctf.sh

      # (Opcional) calcula checksum y lo guarda para el cuerpo de la release
      - name: Compute checksum
        id: sums
        run: |
          sha256sum /tmp/linpeas_ctf.sh | tee sha256.txt
          echo "sha256=$(cut -d' ' -f1 sha256.txt)" >> $GITHUB_OUTPUT

      # Crea/actualiza la release del tag y sube el asset
      - name: Create/Update Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: |
            Release automática generada por GitHub Actions.

            **SHA256**: ${{ steps.sums.outputs.sha256 }}
          draft: false
          prerelease: false
          make_latest: true
          fail_on_unmatched_files: true
          files: |
            /tmp/linpeas_ctf.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

